# Generated by Django 4.2.1 on 2023-05-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpme', '0002_remove_contact_pohne_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(default='', max_length=255),
        ),
    ]
