# Generated by Django 4.2.1 on 2023-05-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpme', '0003_alter_contact_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
    ]
